#!/usr/bin/env bash
# A Bash script that fixes a web server to run Nginx

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replace port 80 with 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# give owner permissions to read and write
chmod 644 /etc/nginx/nginx.conf
# kill the process if it is running
pkill apache2
# now start the nginx service with the new nginx user
sudo -u nginx service nginx start
